import product1 from "@/assets/products/p1.webp";
import product2 from "@/assets/products/p2.webp";
import product3 from "@/assets/products/p3.webp";
import product4 from "@/assets/products/p4.webp";
import product5 from "@/assets/products/p5.webp";
import product6 from "@/assets/products/p6.webp";
import product7 from "@/assets/products/p7.webp";
import product8 from "@/assets/products/p8.webp";
import product9 from "@/assets/products/p9.webp";
import product10 from "@/assets/products/p10.webp";
import product11 from "@/assets/products/p11.webp";
import product12 from "@/assets/products/p12.webp";
import product13 from "@/assets/products/p13.webp";
import product14 from "@/assets/products/p14.webp";
import product15 from "@/assets/products/p15.webp";
import product16 from "@/assets/products/p16.webp";
import product17 from "@/assets/products/p17.webp";
import product18 from "@/assets/products/p18.webp";
import product19 from "@/assets/products/p19.webp";
import product20 from "@/assets/products/p20.webp";
import product21 from "@/assets/products/p21.webp";
import product22 from "@/assets/products/p22.webp";

export const productsList = [
  {
    id: 1,
    title: "Steve Madden Womens Dolly Sandal",
    rating: 4.5,
    price: 3500,
    mrpPrice: 4201,
    description:
      "The perfect recipe for a family game night! Appeals to a wide range of people. Created By National Parks. Parents who had traveled to every single National Park worked together with their board game designer son and created a game to inspire others and help families share their love of the National Parks.",
    size: ["s", "m", "l", "xl"],
    category: "woman",
    thumbelImage: product1,
    backViewImage: product2,
    images: [product1, product2, product3, product4],
    quintity: 20,
    sku: "AB-125486",
    label: "Best Seller",
    availability: "In stock",
    categoty: "Clothes",
  },
  {
    id: 2,
    title: "Zara Women Leather Bag",
    rating: 2.5,
    price: 2540,
    mrpPrice: 3251,
    description:
      "Black printed cotton kameez with embroidery. Comes with matching cotton shalwar and white cotton dupatta.",
    size: ["s", "m", "xl"],
    category: "woman",
    thumbelImage: product3,
    backViewImage: product4,
    images: [product4, product3, product2, product1],
    quintity: 25,
    sku: "ABC-145487",
    availability: "In stock",
    categoty: "Clothes",
  },
  {
    id: 3,
    title: "Travel Leather Backpack",
    price: 1452,
    mrpPrice: "",
    rating: 4.5,
    description:
      "Crimson red dobby texture printed viscose-cotton kameez with golden, copper, olive, orange, pink, yellow, pastel green and mint embroidery. Comes with crimson red cotton shalwar and matching printed vortex-cotton dupatta with tassels.",
    size: ["m", "l", "xl"],
    category: "woman",
    thumbelImage: product5,
    backViewImage: product6,
    images: [product5, product6, product7],
    quintity: 12,
    sku: "GB-125486",
    label: "Limited Stock",
    availability: "In stock",
    categoty: "Clothes",
  },
  {
    id: 4,
    title: "Mint Embroidered Balkan Fusion Theme Shalwar Kameez",
    price: 2540,
    rating: 3.5,
    mrpPrice: 3432,
    description:
      "Brown printed endi silk panjabi with white embroidery. Features in-seam side pockets.",
    size: ["s", "m", "l"],
    category: "man",
    thumbelImage: product7,
    backViewImage: product1,
    images: [product7, product6, product5],
    quintity: 18,
    sku: "BC-125486",
    availability: "Out of stock",
    categoty: "Clothes",
  },
  {
    id: 5,
    title: "Turquoise Printed and Embroidered Viscose-Cotton Shalwar Kameez",
    price: 520,
    mrpPrice: 652,
    rating: 2,
    description:
      "Crimson red dobby texture printed viscose-cotton kameez with golden, copper, olive, orange, pink, yellow, pastel green and mint embroidery. Comes with crimson red cotton shalwar and matching printed vortex-cotton dupatta with tassels.",
    size: ["s", "l", "xl"],
    category: "man",
    thumbelImage: product2,
    backViewImage: product3,
    images: [product2, product3, product4],
    quintity: 14,
    sku: "CB-125486",
    label: "Best Seller",
    availability: "Out of stock",
    categoty: "Clothes",
  },
  {
    id: 6,
    title: "Purple Pabna Cotton Monipuri Buti Saree",
    price: 3500,
    mrpPrice: 4201,
    rating: 3.5,
    description:
      "Green texture printed vortex-viscose-cotton kameez with purple embroidery. Comes with green printed vortex-viscose-cotton shalwar and matching printed viscose-cotton dupatta with tassels.",
    size: ["s", "m", "xl"],
    category: "woman",
    thumbelImage: product1,
    backViewImage: product2,
    images: [product1, product2, product3, product4],
    quintity: 20,
    sku: "AB-125486",
    label: "Best Seller",
    availability: "In stock",
    categoty: "Clothes",
  },
  {
    id: 7,
    title: "iPhone 8 Plus 64GB Full Color",
    price: 3500,
    mrpPrice: 4201,
    rating: 3.5,
    description:
      "Green texture printed vortex-viscose-cotton kameez with purple embroidery. Comes with green printed vortex-viscose-cotton shalwar and matching printed viscose-cotton dupatta with tassels.",
    size: ["s", "m", "xl"],
    category: "woman",
    thumbelImage: product7,
    backViewImage: product8,
    images: [product7, product8, product9, product10],
    quintity: 20,
    sku: "AB-125486",
    label: "Best Seller",
    availability: "In stock",
    categoty: "Smartphones & Tablets",
  },
  {
    id: 8,
    title: "iPhone 6s Plus Red Case",
    price: 3500,
    mrpPrice: 4201,
    rating: 3.5,
    description:
      "Green texture printed vortex-viscose-cotton kameez with purple embroidery. Comes with green printed vortex-viscose-cotton shalwar and matching printed viscose-cotton dupatta with tassels.",
    size: ["s", "m", "xl"],
    category: "woman",
    thumbelImage: product9,
    backViewImage: product10,
    images: [product9, product10, product11, product12],
    quintity: 20,
    sku: "AB-125486",
    label: "Best Seller",
    availability: "In stock",
    categoty: "Smartphones & Tablets",
  },
  {
    id: 9,
    title: "iPhone 7 Plus 64GB Silver",
    price: 3500,
    mrpPrice: 4201,
    rating: 3.5,
    description:
      "Green texture printed vortex-viscose-cotton kameez with purple embroidery. Comes with green printed vortex-viscose-cotton shalwar and matching printed viscose-cotton dupatta with tassels.",
    size: ["s", "m", "xl"],
    category: "woman",
    thumbelImage: product11,
    backViewImage: product12,
    images: [product11, product12, product13, product14],
    quintity: 20,
    sku: "AB-125486",
    label: "Best Seller",
    availability: "In stock",
    categoty: "Smartphones & Tablets",
  },

  {
    id: 10,
    title: "iPhone 7 Plus Pink Silver",
    price: 3500,
    mrpPrice: 4201,
    rating: 3.5,
    description:
      "Green texture printed vortex-viscose-cotton kameez with purple embroidery. Comes with green printed vortex-viscose-cotton shalwar and matching printed viscose-cotton dupatta with tassels.",
    size: ["s", "m", "xl"],
    category: "woman",
    thumbelImage: product13,
    backViewImage: product14,
    images: [product13, product14, product8, product9],
    quintity: 20,
    sku: "AB-125486",
    label: "Best Seller",
    availability: "In stock",
    categoty: "Smartphones & Tablets",
  },

  {
    id: 11,
    title: "Vivo 7 Plus Pink Silver",
    price: 3500,
    mrpPrice: 4201,
    rating: 3.5,
    description:
      "Green texture printed vortex-viscose-cotton kameez with purple embroidery. Comes with green printed vortex-viscose-cotton shalwar and matching printed viscose-cotton dupatta with tassels.",
    size: ["s", "m", "xl"],
    category: "woman",
    thumbelImage: product10,
    backViewImage: product12,
    images: [product10, product12, product8, product9],
    quintity: 20,
    sku: "AB-125486",
    label: "Best Seller",
    availability: "In stock",
    categoty: "Smartphones & Tablets",
  },
  {
    id: 12,
    title: "Omega Automatic Blue Watches",
    price: 3500,
    mrpPrice: 4201,
    rating: 3.5,
    description:
      "Green texture printed vortex-viscose-cotton kameez with purple embroidery. Comes with green printed vortex-viscose-cotton shalwar and matching printed viscose-cotton dupatta with tassels.",
    size: ["s", "m", "xl"],
    category: "woman",
    thumbelImage: product15,
    backViewImage: product16,
    images: [product15, product16, product17, product18],
    quintity: 20,
    sku: "AB-125486",
    label: "Best Seller",
    availability: "In stock",
    categoty: "Jewelry & Watches",
  },
  {
    id: 13,
    title: "Silver Elegant Flower Engagement",
    price: 3500,
    mrpPrice: 4201,
    rating: 3.5,
    description:
      "Green texture printed vortex-viscose-cotton kameez with purple embroidery. Comes with green printed vortex-viscose-cotton shalwar and matching printed viscose-cotton dupatta with tassels.",
    size: ["s", "m", "xl"],
    category: "woman",
    thumbelImage: product19,
    backViewImage: product20,
    images: [product19, product20, product21, product22],
    quintity: 20,
    sku: "AB-125486",
    label: "Best Seller",
    availability: "In stock",
    categoty: "Jewelry & Watches",
  },
  {
    id: 14,
    title: "Red automatic Skeleton Waterproof",
    price: 3500,
    mrpPrice: 4201,
    rating: 3.5,
    description:
      "Green texture printed vortex-viscose-cotton kameez with purple embroidery. Comes with green printed vortex-viscose-cotton shalwar and matching printed viscose-cotton dupatta with tassels.",
    size: ["s", "m", "xl"],
    category: "woman",
    thumbelImage: product17,
    backViewImage: product18,
    images: [product17, product18, product19, product20],
    quintity: 20,
    sku: "AB-125486",
    label: "Best Seller",
    availability: "In stock",
    categoty: "Jewelry & Watches",
  },

  {
    id: 15,
    title: "Rose & Jake 18K Rose Gold Plated",
    price: 3500,
    mrpPrice: 4201,
    rating: 3.5,
    description:
      "Green texture printed vortex-viscose-cotton kameez with purple embroidery. Comes with green printed vortex-viscose-cotton shalwar and matching printed viscose-cotton dupatta with tassels.",
    size: ["s", "m", "xl"],
    category: "woman",
    thumbelImage: product21,
    backViewImage: product22,
    images: [product21, product22, product17, product18],
    quintity: 20,
    sku: "AB-125486",
    label: "Best Seller",
    availability: "In stock",
    categoty: "Jewelry & Watches",
  },
];
